version: '3'
services:
  ffmpeg-top:
    container_name: ffmpeg-top
    image: linuxserver/ffmpeg
    network_mode: host
    restart: unless-stopped
    volumes:
      - "./public:/data"
    environment:
      - FFREPORT=file=/data/top.log:level=24
    command: >
      -re -y -f image2 -loop 1 -i /data/objects_top.jpg
      -vcodec libx264 -f flv -flvflags no_duration_filesize -drop_pkts_on_overflow 1 -attempt_recovery 1 -recovery_wait_time 1
      -loglevel warning
      rtmp://localhost:1935/live/top
    # networks:
    #   - host
